In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt


df = pd.read_stata('data/Authority.dta')
print(df.shape)
#list(df.columns)

(16127, 31)

In [10]:
####setting for descriptive
#contracts awarded btw Jan 2000 and June 2006
#restricted to the simplest types of public works like roadwork construction and repair jobs)
#RP btwn 300,000 euro - 5m euro
#Counties or Municipalities located in Piedmont, lombardy, Veneto, Emilia, and Liguria


idx = df[(df['authority_code']==3091058)].index
df_desc = df.drop(idx)
#df.shape obs = 16127 = original data length

idx2 = df_desc[(df_desc['authority_code']!=3090272) & (df_desc['authority_code']!=3070001) & (df_desc['post_ref_adpt'] == 1)].index
#print(idx2) 1130 obs to be deleted
df_desc =df_desc.drop(idx2)
print(df.shape)
#(14997,31) checked

idx = df_desc[(df_desc['reserve_price']>5000000)|(df_desc['reserve_price']<300000)].index
#print(idx) 6892 obs to be deleted; checked
df_desc = df_desc.drop(idx)
print(df_desc.shape)
#(8105, 31) checked

#5101 obs to be deleted
df_desc = df_desc[(df_desc['ctrl_pop_turin_co_sample']==1) | (df_desc['ctrl_pop_turin_pr_sample']==1) | (df_desc['ctrl_exp_turin_co_sample']==1) | (df_desc['ctrl_exp_turin_pr_sample']==1)]
print(df_desc.shape)
#(3004,31) checked

####complete basic data setting

(16127, 31)
(8105, 31)
(3004, 31)

# Table 1. Descriptive Statistics

In [14]:
#presort

df_pre = df_desc
df_pre['presort'] = np.nan
df_pre.loc[(df_pre['sample']==0)&(df_pre['pre_experience']>=5),'presort'] = 3
#idx = df[(df['presort'].isnull()==True)].index
#print(idx) 1811 obs = NaN checked

#realnm = df[df['presort']==3].index
#print(realnm); starting point, 1193 obs were presrot=3  

df_pre.loc[(df_pre['authority_code']==3090272)&(df_pre['presort'].isnull()==False),'presort'] = 1
#realnm = df[df['presort']==1].index
#print(realnm) 
##121 obs -> presort ==1 chekced

df_pre.loc[(df_pre['authority_code']==3070001)& (df_pre['presort'].isnull() ==False),'presort'] = 2
#realnm = df[df['presort']==2].index
#print(realnm) 
#63 obs -> presort ==2 checked
#print(df.shape) = (3004,32)

df_pre =df_pre.filter(items=['presort', 'fiscal_efficiency', 'reserve_price', 'experience', 'population', 'discount', 'n_bidders', 'overrun_ratio', 'delay_ratio', 'days_to_award'])
idx = df_pre[df_pre['presort'].isnull() == True].index
df_pre = df_pre.drop(idx)
#print(df.shape) #1181 obs dropped, 1193 left (1193,10) checked

df_pre['reserve_price']= df_pre['reserve_price']/1000 #rp = three digits or four
df_pre['population']=df_pre['population']/1000
#df.head()
print(df_pre.shape) 
#(1193,10) checked

#descriptive
df_pre.groupby('presort')[['discount', 'overrun_ratio', 'delay_ratio', 'days_to_award', 'reserve_price',  'n_bidders', 'population', 'experience', 'fiscal_efficiency']].describe()

(1193, 10)

        discount                                                          \
           count       mean       std   min    25%        50%        75%
presort
1.0        121.0  17.071727  5.049077  7.47  12.62  17.430000  20.889999
2.0         63.0  17.323651  5.896641  4.25  15.44  16.870001  19.695001
3.0       1009.0  12.830377  6.167288  0.03   8.66  12.730000  16.830000

                   overrun_ratio            ... experience         \
               max         count      mean  ...        75%    max
presort                                     ...
1.0      30.620001          83.0  5.784887  ...      523.0  523.0
2.0      31.639999          45.0  6.864632  ...      416.0  416.0
3.0      50.000000         672.0  5.298975  ...      251.0  317.0

        fiscal_efficiency                                                    \
                    count      mean       std       min       25%       50%
presort
1.0                 121.0  0.750452  0.034800  0.671798  0.758353  0.758353
2.0                  63.0  0.884224  0.014775  0.870516  0.870516  0.870516
3.0                1009.0  0.813100  0.140129  0.461481  0.739721  0.847338


              75%       max
presort
1.0      0.773652  0.773652
2.0      0.902912  0.902912
3.0      0.922449  1.000000

[3 rows x 72 columns]

In [19]:
#postsort

#same with basic data
'''df_post = pd.read_stata('data/Authority.dta')

idx = df_post[(df_post['authority_code']==3091058)].index
df_post = df_post.drop(idx)
#df_post.shape obs = 16127 = original data length

idx2 = df_post[(df_post['authority_code']!=3090272) & (df_post['authority_code']!=3070001) & (df_post['post_ref_adpt'] == 1)].index
#print(idx2) 1130 obs to be deleted
df_post =df_post.drop(idx2)
print(df_post.shape)
#(14997,31) checked

idx = df_post[(df_post['reserve_price']>5000000)|(df_post['reserve_price']<300000)].index
#print(idx) 6892 obs to be deleted; checked
df_post = df_post.drop(idx)
#print(df_post.shape)
#(8105, 31) checked

df_post = df_post[(df_post['ctrl_pop_turin_co_sample']==1) | (df_post['ctrl_pop_turin_pr_sample']==1) | (df_post['ctrl_exp_turin_co_sample']==1) | (df_post['ctrl_exp_turin_pr_sample']==1)]
#print(df_post.shape)
#(3004,31) checked
##end of the same setting with basic data'''


#post variable
df_post = df_desc
df_post['postsort'] = np.nan
df_post.loc[(df_post['sample']==1)&(df_post['post_experience']>=5),'postsort'] = 3
#idx = df[(df['presort'].isnull()==True)].index
#print(idx) 1811 obs = NaN checked

#realnm = df[df['presort']==3].index
#print(realnm); starting point, 1193 obs were presrot=3  

df_post.loc[(df_post['authority_code']==3090272)&(df_post['postsort'].isnull()==False),'postsort'] = 1
#realnm = df[df['presort']==1].index
#print(realnm) 
##121 obs -> presort ==1 chekced

df_post.loc[(df_post['authority_code']==3070001)& (df_post['postsort'].isnull() ==False),'postsort'] = 2
#realnm = df[df['presort']==2].index
#print(realnm) 
#63 obs -> presort ==2 checked

df_post =df_post.filter(items=['postsort', 'fiscal_efficiency', 'reserve_price', 'experience', 'population', 'discount', 'n_bidders', 'overrun_ratio', 'delay_ratio', 'days_to_award'])
df_post['reserve_price']= df_post['reserve_price']/1000 #rp = three digits or four
df_post['population']=df_post['population']/1000

idx = df_post[df_post['postsort'].isnull() == True].index
df_post = df_post.drop(idx)
print(df_post.shape) #1781 obs deleted checked
df_post.head() # (1223,10)

#descriptive
df_post.groupby('postsort')[['discount', 'overrun_ratio', 'delay_ratio', 'days_to_award', 'reserve_price',  'n_bidders', 'population', 'experience', 'fiscal_efficiency']].describe()

(1223, 10)

,postsort,fiscal_efficiency,reserve_price,experience,population,discount,n_bidders,overrun_ratio,delay_ratio,days_to_award
1124,3.0,0.994788,1043.243,251.0,355.354,19.500000,110.0,4.063087,56.250000,18.0
1126,3.0,0.994788,3881.000,251.0,355.354,16.660000,65.0,1.831525,61.813843,5.0
1170,2.0,0.810613,1570.064,416.0,2242.775,28.709999,25.0,-0.005796,57.303371,NaN
1171,2.0,0.810613,1405.864,416.0,2242.775,26.770000,10.0,-0.196165,0.000000,140.0
1173,2.0,0.810613,3607.835,416.0,2242.775,28.879999,11.0,NaN,14.613180,NaN

* ***Construct Work Category Dummies***

In [2]:
df['OG03_dummy'] = 0
df.loc[(df['work_category']=='OG03')&(df['work_category']!=''),'OG03_dummy'] = 1

df['OG01_dummy'] = 0
df.loc[(df['work_category']=='OG01')&(df['work_category']!=''),'OG01_dummy'] = 1

df['OG_rest_dummy'] = 0
df.loc[(df['OG01_dummy']!=1)&(df['OG03_dummy']!=1)&(df['work_category']!=''),'OG_rest_dummy'] = 1

df['OG_dummy'] = 0
df.loc[df['work_category'].str[0:2] == 'OG','OG_dummy'] = 1

df['OS_dummy'] = 0
df.loc[df['work_category'].str[0:2] == 'OS','OS_dummy'] = 1

#print(df.shape) to check column number (16127,36)
df.head()

,authority_code,year,auth_anno,fpsb_auction,n_bidders,discount,reserve_price,work_category,complex_work,delay_ratio,...,ctrl_exp_turin_co_sample,ctrl_pop_exp_turin_co_sample,ctrl_pop_turin_pr_sample,ctrl_exp_turin_pr_sample,ctrl_pop_exp_turin_pr_sample,OG03_dummy,OG01_dummy,OG_rest_dummy,OG_dummy,OS_dummy
0,543.0,2004.0,1642.0,0.0,3.0,8.150,2.879197e+05,OS24,1.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0,0,1,0,1
1,543.0,2004.0,1642.0,0.0,3.0,8.150,2.879197e+05,OS24,1.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0,0,1,0,1
2,543.0,2004.0,1642.0,0.0,3.0,8.150,2.879197e+05,OS24,1.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0,0,1,0,1
3,3090272.0,2000.0,798.0,0.0,77.0,17.313,8.530979e+05,OG03,1.0,NaN,...,1.0,1.0,1.0,1.0,1.0,1,0,0,1,0
4,3090272.0,2000.0,798.0,0.0,45.0,16.750,1.257377e+06,OG03,1.0,NaN,...,1.0,1.0,1.0,1.0,1.0,1,0,0,1,0

* ***Treated vs Controls***

In [3]:
df['trend'] = df['year'] - 1999

df['trend_treat'] = df['trend']
df.loc[(df['authority_code']!=3090272)&(df['authority_code']!=3070001),'trend_treat'] = 0
#15225 real change made / no zeros in df['trend']
#print(df['trend_treat'].value_counts()) chekced

df['trend_control'] = df['trend']
df.loc[(df['authority_code']==3090272)|(df['authority_code']==3070001),'trend_control'] = 0
#902 real change made
#print(df['trend_control'].value_counts()) checked

* ***PA Specific***

In [4]:
#!pip install econtools
import econtools as econ
import econtools.metrics as mt

Requirement already satisfied: econtools in c:\users\thxkn\anaconda3\lib\site-packages (0.3.2)
Requirement already satisfied: scipy in c:\users\thxkn\anaconda3\lib\site-packages (from econtools) (1.4.1)
Requirement already satisfied: pandas>=0.16.0 in c:\users\thxkn\anaconda3\lib\site-packages (from econtools) (1.0.1)
Requirement already satisfied: numpy>=1.9.2 in c:\users\thxkn\anaconda3\lib\site-packages (from econtools) (1.18.1)
Requirement already satisfied: pytz>=2017.2 in c:\users\thxkn\anaconda3\lib\site-packages (from pandas>=0.16.0->econtools) (2019.3)
Requirement already satisfied: python-dateutil>=2.6.1 in c:\users\thxkn\anaconda3\lib\site-packages (from pandas>=0.16.0->econtools) (2.8.1)
Requirement already satisfied: six>=1.5 in c:\users\thxkn\anaconda3\lib\site-packages (from python-dateutil>=2.6.1->pandas>=0.16.0->econtools) (1.14.0)

In [113]:
#gb = df.sort_values(by='authority_code',ascending=True).groupby('authority_code').count()
#gb.head()
#auth = df['authority_code'].sort_values()

#print(df['authority_code'].value_counts())
#auth_list = df['authority_code'].values.tolist()
#sort된 순서에 따라 1부터 group number부여하기 (total 1999)
#authority_code value값을 list로 만든 후(.tolist), list의 자리(number)+1 값을 group number로 만들면 됨
#python은 0 based counting, for statement range= [,)
#problem: overlapped value are included
#auth_list = list(set(auth_list))
#auth_list.sort() #ascending sorted check

#print(len(auth_list)) #1999개인 것 확인
#for i in range(len(auth_list)):
#auth_list[i] = i + 1'''

3090272.0    498
3070001.0    404
841.0        315
1246.0       261
4.0          235
            ...
1307.0         1
1054.0         1
964.0          1
743.0          1
2016.0         1
Name: authority_code, Length: 1999, dtype: int64

In [5]:
df = df.sort_values(by='authority_code',ascending=True)
#auth = econ.group_id(df, cols = 'authority_code')
#print(auth) #dataframe

auth_list = df['authority_code'].values.tolist()
auth_list = list(set(auth_list))
#본격적으로 df에 id_auth 칼럼을 만들것임
#겹치는 부분 = authority_code야
#id_auth = group_id + 1 if df의 auth code == auth의 code

df['id_auth'] = 0
for i in range(len(df)):
    for j in range(len(auth_list)):
        if df.loc[i,'authority_code'] == auth_list[j]:
            df.loc[i,'id_auth'] = j+1

#for statement check            
#df.head
#print(max(df['id_path']))

In [172]:
#trend_pa_1 = id_auth ==1 인 애들 (trend) 값만 살림 나머지 = 0
#tred_pa_1998, 1999 =0
#test: range = 0~4
'''for i in range(0,5):
    name = 'trend_pa_'+str(i+1)
    df[name] = 0
    for item in df['id_auth'].values.tolist():
        if df.loc[i, 'id_auth'] == item:
            df.loc[i, name] = df.loc[i,'trend']            
    if df.loc[i, 'authority_code']==3090272 or df.loc[i, 'authority_code']==3070001:
        df.loc[i, name] = 0'''

In [178]:
#trend_pa_1997 index = 15224,15225 =11이면 됨
#print(df.loc[15225, trend_pa_1997])
df.head()
print(df.loc[1,'trend_pa_1'])
print(df.loc[1,'trend'])
#stm wrong

0.0
5.0

# Table 2 & 3

In [ ]:
mt.reg(df, 'fpsb_auction','x', )